### ISSUE TITLE
Android application

### ISSUE THREAD

**Issue by fbruetting** [matteocargnelutti/jean-pierre#2]
Hi guys, do you consider creating an Anrdoid application in the future?

**Comment by matteocargnelutti** [comment]
Hi !
Jean-Pierre's web interface is responsive, hence usable on mobile devices through a browser.
I didn't plan on creating a "native" app for it, but it could be great !
The web interface works with a really basic REST API that can be easily used to build an app : please feel free to build your own and share it :-) !
An important limitation to consider though : Jean-Pierre's web interface doesn't use HTTPS by default and has a really minimalistic authentication system, it is not made to be reachable outisde of a local network yet.

**Comment by fbruetting** [comment]
I neither have time nor serious knowledge in web development, but maybe some else will. ;)
