### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by filoor** [matteocargnelutti/jean-pierre#3]
Can i Contribute dutch translation 

"jean-pierre/assets/lang/nl.json" ?

**Comment by matteocargnelutti** [comment]
Hi,

Yes of course, it would be great :) !

**Comment by filoor** [comment]
Hi,

Great I was not able to admit to your project.
Have added as txt attachment. 

[nl.txt](https://github.com/matteocargnelutti/jean-pierre/files/1550692/nl.txt)

**Comment by matteocargnelutti** [comment]
Hi Filoor,

Thanks for your help on the NL version :) !

Here's how to contribute to a project on GitHub : 
1. Fork the repository you want to contribute to
2. Clone your forked repository on your machine and edit it _(in your case, add nl.js to /assets/lang)_
3. Commit and push changes to your forked repository
4. From the Github interface, ask for a "Pull request" : this will ask for a merge between your edited version of Jean-Pierre and mine.
5. And voilà !

You can manage the whole Cloning / Commiting / Pushing part with the GitHub GUI client : https://desktop.github.com/

It works the same way for every project on GitHub : you won't waste your time learning how to do it :).

Thanks in advance,

**Comment by matteocargnelutti** [comment]
I have received and merged your pull request : thanks a lot :) !

**Comment by filoor** [comment]
Thank you :D
