### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by filoor** [matteocargnelutti/jean-pierre#6]
Hi ,

I did follow your steps with a fresh install of "RASPBIAN STRETCH LITE"
but did not get the config step
and also it is not working
see setup process

Processing triggers for libc-bin (2.24-11+deb9u1) ...
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/pi/jean-pierre/env/bin/python3
Also creating executable in /home/pi/jean-pierre/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Collecting astroid==1.5.3 (from -r requirements.txt (line 1))
  Downloading astroid-1.5.3-py2.py3-none-any.whl (269kB)
    100% |████████████████████████████████| 276kB 292kB/s
Collecting certifi==2017.7.27.1 (from -r requirements.txt (line 2))
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 230kB/s
Collecting chardet==3.0.4 (from -r requirements.txt (line 3))
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 456kB/s
Collecting click==6.7 (from -r requirements.txt (line 4))
  Downloading click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 529kB/s
Collecting Flask==0.12.2 (from -r requirements.txt (line 5))
  Downloading Flask-0.12.2-py2.py3-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 348kB/s
Collecting gunicorn==19.7.1 (from -r requirements.txt (line 6))
  Downloading gunicorn-19.7.1-py2.py3-none-any.whl (111kB)
    100% |████████████████████████████████| 112kB 494kB/s
Collecting idna==2.6 (from -r requirements.txt (line 7))
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 545kB/s
Collecting isort==4.2.15 (from -r requirements.txt (line 8))
  Downloading isort-4.2.15-py2.py3-none-any.whl (43kB)
    100% |████████████████████████████████| 51kB 569kB/s
Collecting itsdangerous==0.24 (from -r requirements.txt (line 9))
  Downloading https://www.piwheels.hostedpi.com/simple/itsdangerous/itsdangerous-0.24-py3-none-any.whl
Collecting Jinja2==2.9.6 (from -r requirements.txt (line 10))
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
    100% |████████████████████████████████| 348kB 354kB/s
Collecting lazy-object-proxy==1.3.1 (from -r requirements.txt (line 11))
  Downloading https://www.piwheels.hostedpi.com/simple/lazy-object-proxy/lazy_object_proxy-1.3.1-cp35-cp35m-linux_armv6l.whl (44kB)
    100% |████████████████████████████████| 51kB 539kB/s
Collecting MarkupSafe==1.0 (from -r requirements.txt (line 12))
  Downloading https://www.piwheels.hostedpi.com/simple/markupsafe/MarkupSafe-1.0-cp35-cp35m-linux_armv6l.whl
Collecting mccabe==0.6.1 (from -r requirements.txt (line 13))
  Downloading mccabe-0.6.1-py2.py3-none-any.whl
Collecting olefile==0.44 (from -r requirements.txt (line 14))
  Downloading https://www.piwheels.hostedpi.com/simple/olefile/olefile-0.44-py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 385kB/s
Collecting picamera==1.13 (from -r requirements.txt (line 15))
  Downloading https://www.piwheels.hostedpi.com/simple/picamera/picamera-1.13-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 414kB/s
Collecting Pillow==4.3.0 (from -r requirements.txt (line 16))
  Downloading https://www.piwheels.hostedpi.com/simple/pillow/Pillow-4.3.0-cp35-cp35m-linux_armv6l.whl (1.0MB)
    100% |████████████████████████████████| 1.0MB 90kB/s
Collecting py==1.4.34 (from -r requirements.txt (line 17))
  Downloading py-1.4.34-py2.py3-none-any.whl (84kB)
    100% |████████████████████████████████| 92kB 578kB/s
Collecting pylint==1.7.4 (from -r requirements.txt (line 18))
  Downloading pylint-1.7.4-py2.py3-none-any.whl (640kB)
    100% |████████████████████████████████| 645kB 145kB/s
Collecting pytest==3.2.3 (from -r requirements.txt (line 19))
  Downloading pytest-3.2.3-py2.py3-none-any.whl (187kB)
    100% |████████████████████████████████| 194kB 365kB/s
Collecting pyzbar==0.1.4 (from -r requirements.txt (line 20))
  Downloading pyzbar-0.1.4-py2.py3-none-any.whl
Collecting requests==2.18.4 (from -r requirements.txt (line 21))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 560kB/s
Collecting RPi.GPIO==0.6.3 (from -r requirements.txt (line 22))
  Downloading https://www.piwheels.hostedpi.com/simple/rpi-gpio/RPi.GPIO-0.6.3-cp35-cp35m-linux_armv6l.whl (65kB)
    100% |████████████████████████████████| 71kB 517kB/s
Collecting six==1.11.0 (from -r requirements.txt (line 23))
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting urllib3==1.22 (from -r requirements.txt (line 24))
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 478kB/s
Collecting Werkzeug==0.12.2 (from -r requirements.txt (line 25))
  Downloading Werkzeug-0.12.2-py2.py3-none-any.whl (312kB)
    100% |████████████████████████████████| 317kB 241kB/s
Collecting wrapt==1.10.11 (from -r requirements.txt (line 26))
  Downloading https://www.piwheels.hostedpi.com/simple/wrapt/wrapt-1.10.11-cp35-cp35m-linux_armv6l.whl (64kB)
    100% |████████████████████████████████| 71kB 535kB/s
Requirement already satisfied: setuptools in ./env/lib/python3.5/site-packages (from pytest==3.2.3->-r requirements.txt (line 19))
Installing collected packages: lazy-object-proxy, wrapt, six, astroid, certifi, chardet, click, Werkzeug, itsdangerous, MarkupSafe, Jinja2, Flask, gunicorn, idna, isort, mccabe, olefile, picamera, Pillow, py, pylint, pytest, pyzbar, urllib3, requests, RPi.GPIO
Successfully installed Flask-0.12.2 Jinja2-2.9.6 MarkupSafe-1.0 Pillow-4.3.0 RPi.GPIO-0.6.3 Werkzeug-0.12.2 astroid-1.5.3 certifi-2017.7.27.1 chardet-3.0.4 click-6.7 gunicorn-19.7.1 idna-2.6 isort-4.2.15 itsdangerous-0.24 lazy-object-proxy-1.3.1 mccabe-0.6.1 olefile-0.44 picamera-1.13 py-1.4.34 pylint-1.7.4 pytest-3.2.3 pyzbar-0.1.4 requests-2.18.4 six-1.11.0 urllib3-1.22 wrapt-1.10.11
Requirement already satisfied: pyzbar[scripts] in ./env/lib/python3.5/site-packages
Requirement already satisfied: Pillow>=3.2.0; extra == "scripts" in ./env/lib/python3.5/site-packages (from pyzbar[scripts])
Requirement already satisfied: olefile in ./env/lib/python3.5/site-packages (from Pillow>=3.2.0; extra == "scripts"->pyzbar[scripts])
Traceback (most recent call last):
  File "./jeanpierre.py", line 17, in <module>
    import controllers
  File "/home/pi/jean-pierre/controllers/__init__.py", line 11, in <module>
    from .scanner import Scanner
  File "/home/pi/jean-pierre/controllers/scanner.py", line 19, in <module>
    from PIL import Image as pil_image
  File "/home/pi/jean-pierre/env/lib/python3.5/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
jeanpierre-scanner: available
jeanpierre-web: available
jeanpierre-scanner: added process group
jeanpierre-web: added process group
[:{ End of Jean-Pierre's install script.
Please reboot your Pi in ordrer to let Jean-Pierre boot.

**Comment by matteocargnelutti** [comment]
Hi Filoor,

Sorry I couldn't answer earlier.

First thing first : you do need a Raspberry Pi Camera for Jean-Pierre to work.

Then, when you install Jean-Pierre : 
You must clone this repository and run install.sh, as mentionned in the docs. 
This will create a virtual environment for Jean-Pierre's Python libs, install dependencies and launch two supervisor daemon tasks that are needed by Jean-Pierre : the scanner and the web server.

You don't need to run manually the config utility : if you want to do it though, you first need to launch the virtual environment : 
`source env/bin/activate`

Hope this will help !

**Comment by filoor** [comment]
Hi Matteocargnelutti,

Thank you for your response.
I have a camera  now but still nothing.
After the install reboot my pi but the web server wont start .
and if i try to open the config file manual it wont open also 
See error:

```
pi@raspberrypi:~ $ cd jean-pierre
pi@raspberrypi:~/jean-pierre $ source env/bin/activate
(env) pi@raspberrypi:~/jean-pierre $ ./jeanpierre.py --do config
Traceback (most recent call last):
  File "./jeanpierre.py", line 17, in <module>
    import controllers
  File "/home/pi/jean-pierre/controllers/__init__.py", line 11, in <module>
    from .scanner import Scanner
  File "/home/pi/jean-pierre/controllers/scanner.py", line 19, in <module>
    from PIL import Image as pil_image
  File "/home/pi/jean-pierre/env/lib/python3.5/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
(env) pi@raspberrypi:~/jean-pierre $
```

**Comment by matteocargnelutti** [comment]
Have you installed Jean-Pierre with ./install.sh ? it seems like some dependencies failed to install.

**Comment by filoor** [comment]
Hi,

Yes on the last version of "RASPBIAN STRETCH LITE" "Version:November 2017"

**Comment by filoor** [comment]
```
(env) pi@raspberrypi:~/jean-pierre $ pip install -r requirements.txt;
> Requirement already satisfied: astroid==1.5.3 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 1))
> Requirement already satisfied: certifi==2017.7.27.1 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 2))
> Requirement already satisfied: chardet==3.0.4 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 3))
> Requirement already satisfied: click==6.7 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 4))
> Requirement already satisfied: Flask==0.12.2 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 5))
> Requirement already satisfied: gunicorn==19.7.1 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 6))
> Requirement already satisfied: idna==2.6 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 7))
> Requirement already satisfied: isort==4.2.15 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 8))
> Requirement already satisfied: itsdangerous==0.24 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 9))
> Requirement already satisfied: Jinja2==2.9.6 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 10))
> Requirement already satisfied: lazy-object-proxy==1.3.1 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 11))
> Requirement already satisfied: MarkupSafe==1.0 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 12))
> Requirement already satisfied: mccabe==0.6.1 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 13))
> Requirement already satisfied: olefile==0.44 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 14))
> Requirement already satisfied: picamera==1.13 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 15))
> Requirement already satisfied: Pillow==4.3.0 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 16))
> Requirement already satisfied: py==1.4.34 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 17))
> Requirement already satisfied: pylint==1.7.4 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 18))
> Requirement already satisfied: pytest==3.2.3 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 19))
> Requirement already satisfied: pyzbar==0.1.4 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 20))
> Requirement already satisfied: requests==2.18.4 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 21))
> Requirement already satisfied: RPi.GPIO==0.6.3 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 22))
> Requirement already satisfied: six==1.11.0 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 23))
> Requirement already satisfied: urllib3==1.22 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 24))
> Requirement already satisfied: Werkzeug==0.12.2 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 25))
> Requirement already satisfied: wrapt==1.10.11 in ./env/lib/python3.5/site-packages (from -r requirements.txt (line 26))
> Requirement already satisfied: setuptools in ./env/lib/python3.5/site-packages (from pytest==3.2.3->-r requirements.txt (line 19))

```

**Comment by filoor** [comment]
Hi,

i did give it a try with " Raspbian" not the light version and that works?

**Comment by matteocargnelutti** [comment]
I see you troubleshooted quite a lot ;-). It's not normal that you had to install Raspbian "full" though, as it works on Lite.

My guess is that maybe you installed Jean-Pierre before plugging and setting up the camera : hence, the two supervisor daemons were already launched by install.sh, and migh have caused the problem ?

Install.sh contains all the dependencies needed for Jean-Pierre : note that doing pip install -r requirements.txt isn't enough, has it needs to executes specific scripts for Pillow.

**Comment by filoor** [comment]
Hi Me again
i did te following steps 

`
```
sudo apt-get update 
sudo apt-get upgrade 
sudo rpi-update
sudo apt-get install git
sudo raspi-config (enabeld cam)
sudo reboot
raspistill -o image (to check the cam )
git clone https://github.com/matteocargnelutti/jean-pierre.git
cd jean-pierre
chmod a+x install.sh
./install.sh
````

but still getting the next error 

`
(env) pi@raspberrypi:~/jean-pierre $ ./jeanpierre.py --do config
Traceback (most recent call last):
  File "./jeanpierre.py", line 17, in <module>
    import controllers
  File "/home/pi/jean-pierre/controllers/__init__.py", line 11, in <module>
    from .scanner import Scanner
  File "/home/pi/jean-pierre/controllers/scanner.py", line 19, in <module>
    from PIL import Image as pil_image
  File "/home/pi/jean-pierre/env/lib/python3.5/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
`

**Comment by matteocargnelutti** [comment]
Hi Filoor,
Sorry for the delay.

That's weird : all the dependencies should have been installed with install.sh
Please try the following : 
`sudo apt-get install libjpeg8-dev libopenjpeg2 libopenjpeg-dev`

Thanks,

**Comment by filoor** [comment]
Thank you,

Will try it when i'm at home.

**Comment by filoor** [comment]
I'm getting a error with libopenjpeg2


````
pi@raspberrypi:~/jean-pierre $ sudo apt-get install libjpeg8-dev libopenjpeg2 libopenjpeg-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libopenjpeg2
pi@raspberrypi:~/jean-pierre $
```
`

**Comment by filoor** [comment]
Hi,

After running 
`sudo apt-get install python-pil python-imaging python-imaging-tk`

It did fix the problem it has to do with "raspbian stretch lite"

Thank you for your time

**Comment by matteocargnelutti** [comment]
Hi Filoor,

Sounds great, but it's still weird !
Thanks for letting me know.
