### ISSUE TITLE
Scanner

### ISSUE THREAD

**Issue by filoor** [matteocargnelutti/jean-pierre#7]
Hi 

Will the scanner only work with ean13

**Comment by matteocargnelutti** [comment]
Hi,

Yes it will : the OpenFoodFacts API works with ean-13 barcodes, so it made sense to limit it to that format.
But zbar, the lib that Jean-Pierre uses, allows for detection of virtually any kind of barcode : you can hence easily overwrite this limitation, in /controllers/scanner.py and utils/findproduct.py.
